# Generated by Django 5.0.6 on 2026-04-13 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('cpu', 'Процесор'), ('motherboard', 'Материнська плата'), ('ram', "Оперативна пам'ять"), ('gpu', 'Відеокарта'), ('psu', 'Блок живлення'), ('storage', 'Накопичувач'), ('case', 'Корпус'), ('cooler', 'Кулер')], max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='components/')),
                ('socket', models.CharField(blank=True, max_length=50)),
                ('ram_type', models.CharField(blank=True, choices=[('ddr4', 'DDR4'), ('ddr5', 'DDR5')], max_length=10)),
                ('wattage', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['type', 'brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('warranty', models.PositiveSmallIntegerField(blank=True, help_text='Гарантія в місяцях', null=True)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Довільні характеристики у форматі JSON')),
                ('component', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='catalog.component')),
            ],
        ),
    ]
